on:
  schedule:
    - cron: '30 * * * *' # Run at 30 minutes past every hour
  workflow_dispatch:
  push:
    branches: main
    paths:
      - '2_retriever/**'
      - '.github/workflows/retriever.yml'

name: auto fetcher

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      #actions: write
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install ubuntu dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with: 
          packages: >- 
            libcurl4-openssl-dev 
#            libharfbuzz-dev libfribidi-dev
#            libudunits2-dev libgdal-dev
          version: 1

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          Ncpus: '4'

      - name: Install R dependency
        uses: r-lib/actions/setup-renv@v2
        with:
          profile: '"packages"'
          cache-version: 2

      - name: run main.R
        env:
          SECRET: ${{ secrets.SECRET }}
          DATABASE: ${{ secrets.DATABASE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }} 
          DB_USER: ${{ secrets.DB_USER }}  
        run: Rscript --verbose ./2_retriever/main.R
      
      - name: run experimental.R
        env:
          SECRET: ${{ secrets.SECRET }}
          DATABASE: ${{ secrets.DATABASE_EXP }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }} 
          DB_USER: ${{ secrets.DB_USER }}  
        run: Rscript --verbose ./2_retriever/experimental.R          
          
